module.exports = do ->
  'one_piece'            : url: 'http://mangafox.me/manga/one_piece', format: 1
  'bleach'               : url: 'http://mangafox.me/manga/bleach', format: 1
  'bleach_mp'            : url: 'http://mangapark.com/manga/Bleach', format: 4
  'lucky_star'           : url: 'http://mangapark.com/manga/Lucky-Star', format: 4
  'naruto'               : url: 'http://mangapark.com/manga/Naruto', format: 4
  'nisekoi'              : url: 'http://mangapark.com/manga/nisekoi/s3', format: 4
  'mkm'                  : url: 'http://mangapark.com/manga/minamoto-kun-monogatari/s2', format: 4
  'monster_musume'       : url: 'http://mangapark.com/manga/monster-musume-no-iru-nichijou-inui-takemaru-okayado/s2', format: 4
  'kancolle'             : url: 'http://mangapark.com/manga/kantai-collection-kancolle-itsuka-shizuka-na-umi-de/s2', format: 2
  'kancolle_fu'          : url: 'http://mangapark.com/manga/kantai-collection-kancolle-4-koma-comic-fubuki-ganbarimasu/s2', format: 2
  'kancolle_shima'       : url: 'http://mangapark.com/manga/kantai-collection-kankore-shimakaze-tsumujikaze-no-shoujo', format: 4
  'kancolle_waha'        : url: 'http://mangapark.com/manga/kantai-collection-kancolle-kancolle-e2-98-86-waha-doujinshi/s2', format: 2
  'kancolle_nyagato'     : url: 'http://mangapark.com/manga/kantai-collection-kancolle-nora-senkan-nyagato-san-doujinshi/s2', format: 2
  'kancolle_nagatsuki'   : url: 'http://mangapark.com/manga/kantai-collection-kancolle-secretary-fleet-girl-nagatsuki-chan-doujinshi/s2', format: 4
  'kancolle_haruna'      : url: 'http://mangapark.com/manga/kantai-collection-kancolle-yes-even-if-shes-little-haruna-is-alright-doujinshi/s2', format: 2
  'kancolle_akkg'        : url: 'http://mangapark.com/manga/kantai-collection-kancolle-akkg-doujinshi/s2', format: 2
  'kancolle_alacarte'    : url: 'http://mangapark.com/manga/kantai-collection-kancolle-comic-c3-a0-la-carte-maizuru-naval-district/s2', format: 2
  'kancolle_dairoku'     : url: 'http://mangapark.com/manga/kantai-collection-kancolle-dai-roku-kuchiku-tai-ha-zutto-nakayoshi-doujinshi/s2', format: 2
  'kancolle_dostr'       : url: 'http://mangapark.com/manga/kantai-collection-kancolle-kancolle-dostraight-doujinshi/s2', format: 2
  'kancolle_anthology'   : url: 'http://mangapark.com/manga/kantai-collection-kancolle-anthology-comic-yokosuka-guardian-office-edition/s2', format: 2
  'kancolle_kokuritsu'   : url: 'http://mangapark.com/manga/kantai-collection-kancolle-kokuritsu-kantai-youchien-doujinshi/s2', format: 2
  'kancolle_kongou'      : url: 'http://mangapark.com/manga/kantai-collection-kancolle-kongou-desu-ga-chinjufu-no-kuuki-ga-burning-love-desu-doujinshi/s2', format: 2
  'kancolle_bocchi'      : url: 'http://mangapark.com/manga/kantai-collection-kancolle-watashi-ga-bocchi-nano-wa-chinjufu-no-mina-san-no-okage-doujinshi/s2', format: 2
  'twgok'                : url: 'http://mangapark.com/manga/the-world-god-only-knows/s3', format: 4
  'akuma_no_riddle'      : url: 'http://mangapark.com/manga/akuma-no-riddle-kouga-yun/s3', format: 2
  'amagi_brilliant_park' : url: 'http://mangapark.com/manga/amagi-brilliant-park-gatou-shouji/s1', format: 2
  'baka_to_test'         : url: 'http://mangapark.com/manga/baka-to-test-to-shoukanjuu-inoue-kenji/s2', format: 2
  'd_gray_man'           : url: 'http://mangapark.com/manga/d-gray-man/s3', format: 2
  'jormungand'           : url: 'http://mangapark.com/manga/jormungand/s2', format: 2
  'touhou_deep_red'      : url: 'http://mangapark.com/manga/touhou-deep-red-doujinshi/s2', format: 2
  'touhou_eternal_meek'  : url: 'http://mangapark.com/manga/touhou-eternal-meek-doujinshi/s2', format: 2
  'touhou_usagi'         : url: 'http://mangapark.com/manga/touhou-gatsu-no-usagi-doujinshi/s2', format: 2
