module.exports = do ->
  'bleach'        : 'http://mangafox.me/manga/bleach'
  'one-piece'     : 'http://mangafox.me/manga/one_piece'
  'naruto'        : 'http://mangafox.me/manga/naruto'
  'sk'            : 'http://www.mangahere.com/manga/shaman_king'
  'sk-f'          : 'http://www.mangahere.com/manga/shaman_king_flowers'
  'nisekoi'       : 'http://www.mangahere.com/manga/nisekoi_komi_naoshi'
  'denpa-kyoushi' : 'http://www.mangahere.com/manga/denpa_kyoushi'
  'trinity-seven' : 'http://www.mangahere.com/manga/trinity_seven'
  'mkm'           : 'http://www.mangahere.com/manga/minamoto_kun_monogatari'
  'to-love-ru-d'  : 'http://www.mangahere.com/manga/to_love_ru_darkness'
  'shokugeki'     : 'http://www.mangahere.com/manga/shokugeki_no_soma'
  'shinmai'       : 'http://www.mangahere.com/manga/shinmai_maou_no_keiyakusha'
  'masamune'      : 'http://www.mangahere.com/manga/masamune_kun_no_revenge'
  'eyeshield21'   : 'http://www.mangahere.com/manga/eyeshield_21'
  'gundam-origin' : 'http://www.mangahere.com/manga/mobile_suit_gundam_the_origin'
  'fate-extra'    : 'http://www.mangahere.com/manga/fate_extra'
